//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientWeb.MyEventTimeService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RootObject", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RootObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientWeb.MyEventTimeService.Results resultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ClientWeb.MyEventTimeService.Results results {
            get {
                return this.resultsField;
            }
            set {
                if ((object.ReferenceEquals(this.resultsField, value) != true)) {
                    this.resultsField = value;
                    this.RaisePropertyChanged("results");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Results", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Results : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sunriseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sunsetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string solar_noonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string day_lengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string civil_twilight_beginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string civil_twilight_endField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nautical_twilight_beginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nautical_twilight_endField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string astronomical_twilight_beginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string astronomical_twilight_endField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sunrise {
            get {
                return this.sunriseField;
            }
            set {
                if ((object.ReferenceEquals(this.sunriseField, value) != true)) {
                    this.sunriseField = value;
                    this.RaisePropertyChanged("sunrise");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sunset {
            get {
                return this.sunsetField;
            }
            set {
                if ((object.ReferenceEquals(this.sunsetField, value) != true)) {
                    this.sunsetField = value;
                    this.RaisePropertyChanged("sunset");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string solar_noon {
            get {
                return this.solar_noonField;
            }
            set {
                if ((object.ReferenceEquals(this.solar_noonField, value) != true)) {
                    this.solar_noonField = value;
                    this.RaisePropertyChanged("solar_noon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string day_length {
            get {
                return this.day_lengthField;
            }
            set {
                if ((object.ReferenceEquals(this.day_lengthField, value) != true)) {
                    this.day_lengthField = value;
                    this.RaisePropertyChanged("day_length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string civil_twilight_begin {
            get {
                return this.civil_twilight_beginField;
            }
            set {
                if ((object.ReferenceEquals(this.civil_twilight_beginField, value) != true)) {
                    this.civil_twilight_beginField = value;
                    this.RaisePropertyChanged("civil_twilight_begin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string civil_twilight_end {
            get {
                return this.civil_twilight_endField;
            }
            set {
                if ((object.ReferenceEquals(this.civil_twilight_endField, value) != true)) {
                    this.civil_twilight_endField = value;
                    this.RaisePropertyChanged("civil_twilight_end");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string nautical_twilight_begin {
            get {
                return this.nautical_twilight_beginField;
            }
            set {
                if ((object.ReferenceEquals(this.nautical_twilight_beginField, value) != true)) {
                    this.nautical_twilight_beginField = value;
                    this.RaisePropertyChanged("nautical_twilight_begin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string nautical_twilight_end {
            get {
                return this.nautical_twilight_endField;
            }
            set {
                if ((object.ReferenceEquals(this.nautical_twilight_endField, value) != true)) {
                    this.nautical_twilight_endField = value;
                    this.RaisePropertyChanged("nautical_twilight_end");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string astronomical_twilight_begin {
            get {
                return this.astronomical_twilight_beginField;
            }
            set {
                if ((object.ReferenceEquals(this.astronomical_twilight_beginField, value) != true)) {
                    this.astronomical_twilight_beginField = value;
                    this.RaisePropertyChanged("astronomical_twilight_begin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string astronomical_twilight_end {
            get {
                return this.astronomical_twilight_endField;
            }
            set {
                if ((object.ReferenceEquals(this.astronomical_twilight_endField, value) != true)) {
                    this.astronomical_twilight_endField = value;
                    this.RaisePropertyChanged("astronomical_twilight_end");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyEventTimeService.EventTimeServiceSoap")]
    public interface EventTimeServiceSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем MyEventTimeServiceResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MyEventTimeService", ReplyAction="*")]
        ClientWeb.MyEventTimeService.MyEventTimeServiceResponse MyEventTimeService(ClientWeb.MyEventTimeService.MyEventTimeServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MyEventTimeService", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientWeb.MyEventTimeService.MyEventTimeServiceResponse> MyEventTimeServiceAsync(ClientWeb.MyEventTimeService.MyEventTimeServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestEntity", ReplyAction="*")]
        void TestEntity();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestEntity", ReplyAction="*")]
        System.Threading.Tasks.Task TestEntityAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MyEventTimeServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MyEventTimeService", Namespace="http://tempuri.org/", Order=0)]
        public ClientWeb.MyEventTimeService.MyEventTimeServiceRequestBody Body;
        
        public MyEventTimeServiceRequest() {
        }
        
        public MyEventTimeServiceRequest(ClientWeb.MyEventTimeService.MyEventTimeServiceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MyEventTimeServiceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double lat;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double lng;
        
        public MyEventTimeServiceRequestBody() {
        }
        
        public MyEventTimeServiceRequestBody(double lat, double lng) {
            this.lat = lat;
            this.lng = lng;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MyEventTimeServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MyEventTimeServiceResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientWeb.MyEventTimeService.MyEventTimeServiceResponseBody Body;
        
        public MyEventTimeServiceResponse() {
        }
        
        public MyEventTimeServiceResponse(ClientWeb.MyEventTimeService.MyEventTimeServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MyEventTimeServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientWeb.MyEventTimeService.RootObject MyEventTimeServiceResult;
        
        public MyEventTimeServiceResponseBody() {
        }
        
        public MyEventTimeServiceResponseBody(ClientWeb.MyEventTimeService.RootObject MyEventTimeServiceResult) {
            this.MyEventTimeServiceResult = MyEventTimeServiceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EventTimeServiceSoapChannel : ClientWeb.MyEventTimeService.EventTimeServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EventTimeServiceSoapClient : System.ServiceModel.ClientBase<ClientWeb.MyEventTimeService.EventTimeServiceSoap>, ClientWeb.MyEventTimeService.EventTimeServiceSoap {
        
        public EventTimeServiceSoapClient() {
        }
        
        public EventTimeServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EventTimeServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventTimeServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventTimeServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWeb.MyEventTimeService.MyEventTimeServiceResponse ClientWeb.MyEventTimeService.EventTimeServiceSoap.MyEventTimeService(ClientWeb.MyEventTimeService.MyEventTimeServiceRequest request) {
            return base.Channel.MyEventTimeService(request);
        }
        
        public ClientWeb.MyEventTimeService.RootObject MyEventTimeService(double lat, double lng) {
            ClientWeb.MyEventTimeService.MyEventTimeServiceRequest inValue = new ClientWeb.MyEventTimeService.MyEventTimeServiceRequest();
            inValue.Body = new ClientWeb.MyEventTimeService.MyEventTimeServiceRequestBody();
            inValue.Body.lat = lat;
            inValue.Body.lng = lng;
            ClientWeb.MyEventTimeService.MyEventTimeServiceResponse retVal = ((ClientWeb.MyEventTimeService.EventTimeServiceSoap)(this)).MyEventTimeService(inValue);
            return retVal.Body.MyEventTimeServiceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientWeb.MyEventTimeService.MyEventTimeServiceResponse> ClientWeb.MyEventTimeService.EventTimeServiceSoap.MyEventTimeServiceAsync(ClientWeb.MyEventTimeService.MyEventTimeServiceRequest request) {
            return base.Channel.MyEventTimeServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientWeb.MyEventTimeService.MyEventTimeServiceResponse> MyEventTimeServiceAsync(double lat, double lng) {
            ClientWeb.MyEventTimeService.MyEventTimeServiceRequest inValue = new ClientWeb.MyEventTimeService.MyEventTimeServiceRequest();
            inValue.Body = new ClientWeb.MyEventTimeService.MyEventTimeServiceRequestBody();
            inValue.Body.lat = lat;
            inValue.Body.lng = lng;
            return ((ClientWeb.MyEventTimeService.EventTimeServiceSoap)(this)).MyEventTimeServiceAsync(inValue);
        }
        
        public void TestEntity() {
            base.Channel.TestEntity();
        }
        
        public System.Threading.Tasks.Task TestEntityAsync() {
            return base.Channel.TestEntityAsync();
        }
    }
}
